---
- hosts: mysql
  remote_user: root
  tasks:

  - name: Clonando repo con los checks de nrpe
    git:
      repo: https://github.com/jlizano99/nagios.git
      dest: /opt/nagios/
      clone: yes      

  - name: Comentando las lineas de command en el nrpe.cfg
    replace:
      path: /usr/local/nagios/etc/nrpe.cfg
      regexp: 'command'
      replace: '#command'

  - name: Agregar lineas de commands al nrpe.cfg
    lineinfile:
      path: /usr/local/nagios/etc/nrpe.cfg
      line: "{{ item }}"
    with_items:
       - 'command[check_users]=/usr/local/nagios/libexec/check_users -w 5 -c 10'
       - 'command[check_load]=/usr/local/nagios/libexec/check_load -w 15,10,5 -c 30,25,20'
       - 'command[check_root]=/usr/local/nagios/libexec/check_disk -w 20% -c 10% -p /dev/sda2'
       - 'command[check_swap]=/usr/local/nagios/libexec/check_swap -w 20% -c 10%'
       - '#command[check_mem]=/usr/local/nagios/libexec/check_mem.pl -u -w 75 -c 85'
       - 'command[check_uptime]=/usr/local/nagios/libexec/check_uptime'
       - 'command[check_service_asterisk]=/usr/local/nagios/libexec/check_procs -c @0:0 -C asterisk'
       - 'command[check_memory]=/usr/local/nagios/libexec/check_mem -w 85 -c 95 -W 40 -C 70'  


  - name: Copiar repositorios del nfs al /etc/yum.repos.d/
    copy:
      src: "{{ item }}"
      dest: /usr/local/nagios/libexec/
      mode: 0777
      remote_src: yes
    with_items:
       - '/opt/nagios/check_users'
       - '/opt/nagios/check_load'
       - '/opt/nagios/check_disk'
       - '/opt/nagios/check_swap'
       - '/opt/nagios/check_mem.pl'
       - '/opt/nagios/check_procs'
       - '/opt/nagios/check_nrpe'
       - '/opt/nagios/check_uptime'
       - '/opt/nagios/check_mem'

  - name: Iniciar servicio nagios nrpe
    systemd:
      state: restarted
      name: nrpe
