---
- hosts: pre_checks_ocp4
  remote_user: root
  tasks:

  - name: Instalar librerias necesarias para trabajar
    yum:
      name:
        - git
        - screen
        - nano
        - vim
        - net-tools
        - wget
        - unzip
        - curl
        - nfs-utils
        - bind-utils
      state: present

  - name: Detener servicio firewalld
    systemd:
      state: stopped
      name: firewalld.service

  - name: Deshabilitar servicio firewalld
    systemd:
      name: firewalld.service
      enabled: no
      masked: no

  - name: Deshabilitar SELinux
    selinux:
      state: disabled

  - name: Reiniciar las máquinas para hacer todos los cambios sean efectivos
    reboot:
      reboot_timeout: 120

  - name: Esperar 1 minuto mientras las máquinas inician
    wait_for_connection:
      delay: 30
      timeout: 60

- hosts: dns.mycluster.example.com
  remote_user: root
  tasks:

  - name: Instalar paquete para el DNS
    yum:
      name:
        - dnsmasq
      state: present

  - name: Hacer backup del dnsmasq.conf
    copy:
      src: /etc/dnsmasq.conf
      dest: /etc/dnsmasq.conf.bk
      owner: root
      group: root
      mode: '0644'
      remote_src: yes
      backup: yes

  - name: Eliminar archivo dnsmasq.conf
    file:
      state: absent
      path: "/etc/dnsmasq.conf"

  - name: Crear archivo dnsmasq vacio
    file:
      path: "/etc/dnsmasq.conf"
      state: touch

  - name: Copiar archivo template de dnsmasq al servidor
    template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf

  - name: Crear archivo hosta para dnsmasq vacio
    file:
      path: "/etc/dnsmasq.openshift.addnhosts"
      state: touch

  - name: Copiar archivo template de hosts para dnsmasq al servidor
    template:
      src: dnsmasq.openshift.addnhosts.j2
      dest: /etc/dnsmasq.openshift.addnhosts

  - name: Iniciar servicio dnsmasq
    systemd:
      state: started
      name: dnsmasq

  - name: Habilitar servicio dnsmasq
    systemd:
      name: dnsmasq
      enabled: yes
      masked: no

- hosts: loadbalancer.mycluster.example.com
  remote_user: root
  tasks:

  - name: Instalar paquetes para el balanceador
    yum:
      name:
        - haproxy
      state: present

  - name: Hacer backup del haproxy.cfg
    copy:
      src: /etc/haproxy/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg.bk
      owner: root
      group: root
      mode: '0644'
      remote_src: yes
      backup: yes

  - name: Eliminar archivo haproxy.cfg
    file:
      state: absent
      path: "/etc/haproxy/haproxy.cfg"

  - name: Crear archivo haproxy.cfg
    file:
      path: "/etc/haproxy/haproxy.cfg"
      state: touch

  - name: Copiar archivo template de haproxy al servidor
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: Iniciar servicio haproxy
    systemd:
      state: started
      name: haproxy

  - name: Habilitar servicio haproxy
    systemd:
      name: haproxy
      enabled: yes
      masked: no

- hosts: http.mycluster.example.com
  remote_user: root
  tasks:

  - name: Instalar paquetes para el httpd
    yum:
      name:
        - httpd
      state: present

  - name: Creacion de directorios de httpd para los ignition files y las images de RHCOS
    file:
      path: "{{ item }}"
      state: directory
    with_items:
       - '/var/www/html/ignition'
       - '/var/www/html/images'       

  - name: Hacer backup del config de httpd
    copy:
      src: /etc/httpd/conf/httpd.conf
      dest: /etc/httpd/conf/httpd.conf.bk
      owner: root
      group: root
      mode: '0644'
      remote_src: yes
      backup: yes

  - name: Cambiando el puerto del servidor http de 80 a 8080
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen 8080

  - name: Creacion de directorios de httpd para los ignition files y las images de RHCOS
    file:
      path: "{{ item }}"
      state: directory
    with_items:
       - '/var/www/html/ignition'
       - '/var/www/html/images'

  - name: Copiar images de RHCOS
    copy:
      src: "{{ item }}"
      dest: /var/www/html/images/
      owner: root
      group: root
      mode: '0777'
    with_items:
       - '/home/jlizano/Downloads/rhcos-4.2.0-x86_64-installer-initramfs.img'
       - '/home/jlizano/Downloads/rhcos-4.2.0-x86_64-installer-kernel'
       - '/home/jlizano/Downloads/rhcos-4.2.0-x86_64-metal-bios.raw.gz'
       - '/home/jlizano/Downloads/rhcos-4.2.0-x86_64-installer.iso' 

  - name: Reiniciar servicio httpd
    systemd:
      state: restarted
      name: httpd

  - name: Habilitar servicio httpd
    systemd:
      name: httpd
      enabled: yes
      masked: no